version: '3.4'

services:
  test.book:
    image: ${DOCKER_REGISTRY-}testbook
    build:
      context: .
      dockerfile: test.book/Dockerfile
    networks:
        - "guestbook"
    depends_on:
        - "postgres_db"
    ports:
        - '8080:8080'
        - '8081:8081'
  postgres_db:
    image: postgres:latest
    container_name: PostgresCont 
    restart: always
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres123
    ports:
        - '5432:5432'
    volumes:
        - postgres_db:/var/lib/postgresql/data
    networks:
        - "guestbook"
volumes:
  postgres_db:
    driver: local
networks:
  guestbook:
    driver: bridge  